title: "Brian Zelip"

author:
  name: Brian Zelip
  handle: bzelip
  email: bzelip@gmail.com
  description: Library and Information Science student interested in creating efficient user interfaces and exploring data.

permalink: pretty
baseurl: "/jekyll-test"
highlighter: pygments
